### ISSUE TITLE
Can we test it since there's no hardware anymore?

### ISSUE THREAD

**Issue by Wenfeng-GAO** [infiniot/infiniot-web#3]
As the title said, how to solve this problem.
And do we still have the server which holds and web and android app?

**Comment by mincong-h** [comment]
> Can we test it since there's no hardware anymore?

- We can not use the IoT solution to test infiniot-web, because we don't have Libelium anymore. Communication with hardware is only testable when @ShuyuYANG finishes her development for Raspberry Pi.
- We can test infiniot-web using Maven including unit tests<sup>[1]</sup> and integration tests<sup>[2]</sup>. And infiniot-web has random data generator to provide data for Android.

> Do we still have the server which holds web and android app?

- We still have the server PING32 which hosts the previous web application PING32J. As for the new one, _infiniot-web_, **it can only be launched in localhost**. What I'm planning to do is something like this:

      $ git clone https://github.com/infiniot/infiniot-web.git
      $ cd infiniot-web
      $ mvn clean install
      $ mvn:exec start

    Once the web server started in localhost, you can start infiniot-android and test it.

- The server doesn't contain the Android App PING32A.

We need to discuss details about the web hosting services, but let's do it in other issue.

<sup>[1]</sup> Not implemented yet.
<sup>[2]</sup> Not implemented yet.

**Comment by Wenfeng-GAO** [comment]
Cool for me.
