### ISSUE TITLE
Why not push on the db export file

### ISSUE THREAD

**Issue by Wenfeng-GAO** [infiniot/infiniot-web#6]
As title.
So that we can run the app locally.

**Comment by mincong-h** [comment]
> Why not upload the db export file

**System's modularity.** Because db and web server are two different modules of the project. I don't want to mix them. In particular, the folder `src/main/resources` is designed for the Application/Library resources according to [Maven Standard Directory Layout][mvn-layout]. It means that only those resources used in runtime should be shipped.

**Security.** I don't know how to ensure the security if we make the DB file open-source. Or let's say, how to do the open-source judiciously.

> So that we can run the app locally

This is good question. We can't for instant ...

I was planned to refactored the db dependency from MySQL to H2, an in-memory lightweight database made by Hibernate. So that we can still run the app locally even without the MySQL. But I didn't succeed. I'll do it in the future.

[mvn-layout]: https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html

**Comment by Wenfeng-GAO** [comment]
Or we put the db file out of `src/main`, with `.gitignore` `pom.xml` and `README.md` for example, and tell others how to setup it in `README`.

I think since we make this project open-source, everyone can read and use our code, it's unfair to give someone a website code without db structure. In that case others need to dug into source code to find out db structure in order to use it or run the demo.

For *Security* reason, I don't know if we have rights to open source the fire data.

Keep in discuss.

**Comment by mincong-h** [comment]
> it's unfair to give someone a website code without db structure ...

I agree with you. We should include the db structure. At the first step, at least they can run the demo. Issue #7 is created for it.

> For Security reason, I don't know if we have rights to open source the fire data.

Let's include only the structure. We do not provide any real data, in particular the data which do not belong to us.
